# Generated by Django 4.2.11 on 2024-12-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=180)),
                ('priority', models.CharField(choices=[('M', 'MEDIUM'), ('L', 'LOW'), ('H', 'HIGH')], max_length=1)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
