# Generated by Django 4.2.11 on 2024-12-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('M', 'MEDIUM'), ('H', 'HIGH'), ('L', 'LOW')], max_length=1),
        ),
    ]
