# Generated by Django 4.2.11 on 2024-12-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todo_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('L', 'LOW'), ('M', 'MEDIUM'), ('H', 'HIGH')], max_length=1),
        ),
    ]
