# Generated by Django 4.2.11 on 2024-12-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_todo_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.CharField(default='No description', max_length=180),
        ),
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('N', 'NONE'), ('L', 'LOW'), ('M', 'MEDIUM'), ('H', 'HIGH')], default='N', max_length=1),
        ),
    ]
